##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - autoconf
    - automake
    - autotools-dev
    - autopoint
#    - binutils-dev #make check/distcheck
    - clang
    - clang-tools
    - cmake
    - cppcheck
    - debhelper
    - git
    - gcr
    - gir1.2-gcr-3
    - libgcr-3-dev
    - libgcr-base-3-1
    - libgcr-ui-3-1
#    - kdelibs-bin #make check/distcheck
    - libboost-dev
    - libboost-system-dev
    - libcrypto++-dev
    - libgd-dev
    - libgeoip-dev
    - libglib2.0-dev
    - libpng-dev
    - libpulse-dev
    - libpulse-mainloop-glib0
    - libpulse0
    - gir1.2-polkit-1.0
    - gtk-doc-tools
    - libpolkit-agent-1-0
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-0
    - libpolkit-gobject-1-dev
    - libpolkit-qt5-1-1
    - libsecret-1-0
    - libsecret-1-dev
    - libsecret-common
#    - libqt4-dev #make check/distcheck
#    - libqt4-dev-bin #make check/distcheck
    - libreadline-dev
    - libpam-gnome-keyring
    - libpam-modules
    - libpam-modules-bin
    - libpam-runtime
    - libpam-systemd
    - libpam0g
    - libpam0g-dev

    - libupnp-dev
    - libwxbase3.0-dev #sid
    - meson
    - libfeedback-dev
    - libgnome-desktop-3-dev
    - libhandy-1-dev
    - libnm-dev
    - pandoc
    - phoc
    - pastebinit
    - gir1.2-upowerglib-1.0
    - libcpupower1
    - libupower-glib-dev
    - libupower-glib3
    - upower
    - wx3.0-i18n
    - zlib1g-dev
    - libgudev-1.0-dev
    - libcallaudio-dev

variables:
#  - CPPFLAGS="-Wall -Woverloaded-virtual -Wextra -Wshadow -Wformat-nonliteral -Werror=format-security -Wpointer-arith -Wcast-align -Wmissing-declarations -Wredundant-decls"
  - CXXFLAGS="-Wall -Woverloaded-virtual -Wextra -Wshadow -Wformat-nonliteral -Werror=format-security -Wpointer-arith -Wcast-align -Wmissing-declarations -Wredundant-decls -Wall -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wpointer-arith -Wredundant-decls -Wshadow -Werror=format-security -Wunused-macros"
  - CFLAGS="-Wall -Wextra -Wshadow -Wformat-nonliteral -Werror=format-security -Wpointer-arith -Wcast-align -Wmissing-declarations -Wredundant-decls -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Werror=format-security -Wunused-macros"

before_scripts:
  - SECONDS=0
  - export TITLECPPCHECK="${REPO_NAME} (cppcheck `dpkg -s cppcheck|grep -i version|cut -d " " -f 2`)"
  - cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  - cppcheck-htmlreport --title="$TITLECPPCHECK" --file=cppcheck.xml --report-dir=cppcheck-htmlreport

build_scripts:
#  - mkdir ../clang
#  - cp -dpR . ../clang
#  - cd ../clang
  - export TITLESCANBUILD="${REPO_NAME} (clang-tools `dpkg -s clang-tools|grep -i version|cut -d " " -f 2`) - scan-build results"
  - mkdir html-report
  - cppcheck --enable=warning,style,performance,portability,information,missingInclude . 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}

  - scan-build $CHECKERS --html-title="$TITLESCANBUILD" --keep-cc -o html-report meson -Dgtk_doc=true . _build 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - scan-build $CHECKERS --html-title="$TITLESCANBUILD" --keep-cc -o html-report ninja -C _build 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo "Total time $(($SECONDS / 60)) minutes and $(($SECONDS % 60))" 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Errors detected in the build `cat ./html-report/output_${TRAVIS_COMMIT} | grep ' error:' | grep -v "\[" | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Warnings detected in the logs `cat ./html-report/output_${TRAVIS_COMMIT} | grep -i warning | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
# - tar -zcf phosh_clang_htmlreport.tar.gz phosh_clang_htmlreport
# - curl -F file=@phosh_clang_htmlreport.tar.gz -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
#  - cd ../rootdir

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
#  - make check
#  - make distcheck
#  - make clean
#  - make distclean
